type: mpc
mpc:
  model_name: pointRobot
  n: 3
  time_horizon: 20
  time_step: 0.05
  slack: False
  interval: 1
  initialization: "current_state"
  constraints:
    #- 'RadialConstraints'
    - 'SelfCollisionAvoidanceConstraints'
    - 'JointLimitConstraints'
    - 'InputLimitConstraints'
    - 'VelLimitConstraints'
  objectives:
    - 'GoalReaching'
    - 'ConstraintAvoidance'
  weights:
    w: 1.0
    wvel: [1.0, 1.0, 1.0]
    ws: 1e10
    wu: 0.1
    wobst: 0.05
    wconstr: [0.5, 0.0, 0.0, 0.0]
  number_obstacles: 1
  control_mode: "acc"
robot:
  collision_links: 
    - base_link
  selfCollision:
    pairs:  []
  urdf_file: pointRobot.urdf
  root_link: ee_link
  end_link: base_link
  base_type: holonomic
example:
  debug: False
