mpc_planner_node:
    ros__parameters:
      type: mpc
      mpc:
        model_name: pointRobot
        n: 3
        time_horizon: 10
        time_step: 0.05
        slack: False
        interval: 1
        initialization: "current_state"
        constraints: 
          - InputLimitConstraints
          - VelLimitConstraints
        objectives:
         - 'GoalPoseReaching'
         #- 'HeadingReaching'
        weights:
         w: 1.0
         w_goal_angle: 0.5
         w_heading: 1.0
         wvel: [0.0, 0.0, 0.0, 0.0, 0.00]
         ws: 1e10
         wu: 0.1
         wobst: 0.5
        number_obstacles: 1
        control_mode: "vel"
      robot:
        collision_links:
         - base_link
        selfCollision:
         pairs:  []
        urdf_file: pointRobot.urdf
        root_link: ee_link
        end_link: base_link
        base_type: holonomic #diffdrive
      example:
        debug: False
        floating: True
