/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) jackal_n3_01_H10_noSlack_model_ ## ID
#endif

#include <math.h> 
#include "jackal_n3_01_H10_noSlack_model.h"

#ifndef casadi_real
#define casadi_real jackal_n3_01_H10_noSlack_float
#endif

#ifndef casadi_int
#define casadi_int solver_int32_default
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#if 0
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s1[31] = {27, 1, 0, 27, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[18] = {1, 10, 0, 1, 2, 3, 3, 3, 3, 3, 3, 4, 5, 0, 0, 0, 0, 0};
static const casadi_int casadi_s4[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s5[26] = {11, 10, 0, 3, 6, 9, 9, 9, 9, 9, 9, 11, 13, 0, 1, 2, 0, 3, 4, 0, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s6[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s7[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s8[13] = {2, 8, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1};
static const casadi_int casadi_s9[16] = {8, 8, 0, 2, 4, 5, 5, 5, 5, 5, 5, 2, 6, 2, 6, 7};

/* jackal_n3_01_H10_noSlack_objective_0:(i0[10],i1[27])->(o0,o1[1x10,5nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a3, a4, a5, a6, a7, a8, a9;
  a0=2.0000000000000001e-01;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a2=(a0*a2);
  a3=arg[0]? arg[0][0] : 0;
  a2=(a2+a3);
  a4=arg[1]? arg[1][17] : 0;
  a2=(a2-a4);
  a4=arg[1]? arg[1][20] : 0;
  a5=(a4*a2);
  a6=(a2*a5);
  a7=sin(a1);
  a7=(a0*a7);
  a8=arg[0]? arg[0][1] : 0;
  a7=(a7+a8);
  a9=arg[1]? arg[1][18] : 0;
  a7=(a7-a9);
  a9=arg[1]? arg[1][21] : 0;
  a10=(a9*a7);
  a11=(a7*a10);
  a6=(a6+a11);
  a11=arg[1]? arg[1][19] : 0;
  a12=arg[1]? arg[1][22] : 0;
  a12=(a12*a11);
  a11=(a11*a12);
  a6=(a6+a11);
  a11=arg[1]? arg[1][23] : 0;
  a12=cos(a1);
  a12=(a0*a12);
  a12=(a12+a3);
  a13=arg[1]? arg[1][1] : 0;
  a12=(a12-a13);
  a13=casadi_sq(a12);
  a14=sin(a1);
  a14=(a0*a14);
  a14=(a14+a8);
  a8=arg[1]? arg[1][2] : 0;
  a14=(a14-a8);
  a8=casadi_sq(a14);
  a13=(a13+a8);
  a8=arg[1]? arg[1][3] : 0;
  a8=casadi_sq(a8);
  a13=(a13+a8);
  a13=sqrt(a13);
  a8=arg[1]? arg[1][4] : 0;
  a8=(a13-a8);
  a15=arg[1]? arg[1][0] : 0;
  a8=(a8-a15);
  a11=(a11/a8);
  a15=arg[1]? arg[1][25] : 0;
  a16=arg[1]? arg[1][5] : 0;
  a3=(a3-a16);
  a15=(a15/a3);
  a16=(a11+a15);
  a17=arg[1]? arg[1][26] : 0;
  a18=arg[0]? arg[0][8] : 0;
  a19=arg[1]? arg[1][11] : 0;
  a19=(a18-a19);
  a17=(a17/a19);
  a16=(a16+a17);
  a6=(a6+a16);
  a16=arg[1]? arg[1][15] : 0;
  a20=(a16*a18);
  a21=(a18*a20);
  a22=arg[0]? arg[0][9] : 0;
  a23=arg[1]? arg[1][16] : 0;
  a24=(a23*a22);
  a25=(a22*a24);
  a21=(a21+a25);
  a6=(a6+a21);
  if (res[0]!=0) res[0][0]=a6;
  a4=(a4*a2);
  a5=(a5+a4);
  a15=(a15/a3);
  a12=(a12+a12);
  a11=(a11/a8);
  a13=(a13+a13);
  a11=(a11/a13);
  a12=(a12*a11);
  a15=(a15+a12);
  a15=(a5-a15);
  if (res[1]!=0) res[1][0]=a15;
  a9=(a9*a7);
  a10=(a10+a9);
  a14=(a14+a14);
  a14=(a14*a11);
  a11=(a10-a14);
  if (res[1]!=0) res[1][1]=a11;
  a11=sin(a1);
  a12=(a0*a12);
  a11=(a11*a12);
  a12=cos(a1);
  a14=(a0*a14);
  a12=(a12*a14);
  a11=(a11-a12);
  a12=cos(a1);
  a10=(a0*a10);
  a12=(a12*a10);
  a11=(a11+a12);
  a1=sin(a1);
  a0=(a0*a5);
  a1=(a1*a0);
  a11=(a11-a1);
  if (res[1]!=0) res[1][2]=a11;
  a16=(a16*a18);
  a20=(a20+a16);
  a17=(a17/a19);
  a20=(a20-a17);
  if (res[1]!=0) res[1][3]=a20;
  a23=(a23*a22);
  a24=(a24+a23);
  if (res[1]!=0) res[1][4]=a24;
  return 0;
}

int jackal_n3_01_H10_noSlack_objective_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

int jackal_n3_01_H10_noSlack_objective_0_alloc_mem(void) {
  return 0;
}

int jackal_n3_01_H10_noSlack_objective_0_init_mem(int mem) {
  return 0;
}

void jackal_n3_01_H10_noSlack_objective_0_free_mem(int mem) {
}

int jackal_n3_01_H10_noSlack_objective_0_checkout(void) {
  return 0;
}

void jackal_n3_01_H10_noSlack_objective_0_release(int mem) {
}

void jackal_n3_01_H10_noSlack_objective_0_incref(void) {
}

void jackal_n3_01_H10_noSlack_objective_0_decref(void) {
}

casadi_int jackal_n3_01_H10_noSlack_objective_0_n_in(void) { return 2;}

casadi_int jackal_n3_01_H10_noSlack_objective_0_n_out(void) { return 2;}

casadi_real jackal_n3_01_H10_noSlack_objective_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* jackal_n3_01_H10_noSlack_objective_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* jackal_n3_01_H10_noSlack_objective_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* jackal_n3_01_H10_noSlack_objective_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* jackal_n3_01_H10_noSlack_objective_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

int jackal_n3_01_H10_noSlack_objective_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* jackal_n3_01_H10_noSlack_inequalities_0:(i0[10],i1[27])->(o0[11],o1[11x10,13nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8;
  a0=2.0000000000000001e-01;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a2=(a0*a2);
  a3=arg[0]? arg[0][0] : 0;
  a2=(a2+a3);
  a4=arg[1]? arg[1][1] : 0;
  a2=(a2-a4);
  a4=casadi_sq(a2);
  a5=sin(a1);
  a5=(a0*a5);
  a6=arg[0]? arg[0][1] : 0;
  a5=(a5+a6);
  a7=arg[1]? arg[1][2] : 0;
  a5=(a5-a7);
  a7=casadi_sq(a5);
  a4=(a4+a7);
  a7=arg[1]? arg[1][3] : 0;
  a7=casadi_sq(a7);
  a4=(a4+a7);
  a4=sqrt(a4);
  a7=arg[1]? arg[1][4] : 0;
  a7=(a4-a7);
  a8=arg[1]? arg[1][0] : 0;
  a7=(a7-a8);
  if (res[0]!=0) res[0][0]=a7;
  a7=arg[1]? arg[1][5] : 0;
  a7=(a3-a7);
  if (res[0]!=0) res[0][1]=a7;
  a7=arg[1]? arg[1][8] : 0;
  a7=(a7-a3);
  if (res[0]!=0) res[0][2]=a7;
  a7=arg[1]? arg[1][6] : 0;
  a7=(a6-a7);
  if (res[0]!=0) res[0][3]=a7;
  a7=arg[1]? arg[1][9] : 0;
  a7=(a7-a6);
  if (res[0]!=0) res[0][4]=a7;
  a7=arg[1]? arg[1][7] : 0;
  a7=(a1-a7);
  if (res[0]!=0) res[0][5]=a7;
  a7=arg[1]? arg[1][10] : 0;
  a7=(a7-a1);
  if (res[0]!=0) res[0][6]=a7;
  a7=arg[0]? arg[0][8] : 0;
  a6=arg[1]? arg[1][11] : 0;
  a6=(a7-a6);
  if (res[0]!=0) res[0][7]=a6;
  a6=arg[1]? arg[1][13] : 0;
  a6=(a6-a7);
  if (res[0]!=0) res[0][8]=a6;
  a6=arg[0]? arg[0][9] : 0;
  a7=arg[1]? arg[1][12] : 0;
  a7=(a6-a7);
  if (res[0]!=0) res[0][9]=a7;
  a7=arg[1]? arg[1][14] : 0;
  a7=(a7-a6);
  if (res[0]!=0) res[0][10]=a7;
  a7=(a2/a4);
  if (res[1]!=0) res[1][0]=a7;
  a7=1.;
  if (res[1]!=0) res[1][1]=a7;
  a6=-1.;
  if (res[1]!=0) res[1][2]=a6;
  a3=(a5/a4);
  if (res[1]!=0) res[1][3]=a3;
  if (res[1]!=0) res[1][4]=a7;
  if (res[1]!=0) res[1][5]=a6;
  a5=(a5+a5);
  a3=cos(a1);
  a3=(a0*a3);
  a5=(a5*a3);
  a2=(a2+a2);
  a1=sin(a1);
  a0=(a0*a1);
  a2=(a2*a0);
  a5=(a5-a2);
  a4=(a4+a4);
  a5=(a5/a4);
  if (res[1]!=0) res[1][6]=a5;
  if (res[1]!=0) res[1][7]=a7;
  if (res[1]!=0) res[1][8]=a6;
  if (res[1]!=0) res[1][9]=a7;
  if (res[1]!=0) res[1][10]=a6;
  if (res[1]!=0) res[1][11]=a7;
  if (res[1]!=0) res[1][12]=a6;
  return 0;
}

int jackal_n3_01_H10_noSlack_inequalities_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

int jackal_n3_01_H10_noSlack_inequalities_0_alloc_mem(void) {
  return 0;
}

int jackal_n3_01_H10_noSlack_inequalities_0_init_mem(int mem) {
  return 0;
}

void jackal_n3_01_H10_noSlack_inequalities_0_free_mem(int mem) {
}

int jackal_n3_01_H10_noSlack_inequalities_0_checkout(void) {
  return 0;
}

void jackal_n3_01_H10_noSlack_inequalities_0_release(int mem) {
}

void jackal_n3_01_H10_noSlack_inequalities_0_incref(void) {
}

void jackal_n3_01_H10_noSlack_inequalities_0_decref(void) {
}

casadi_int jackal_n3_01_H10_noSlack_inequalities_0_n_in(void) { return 2;}

casadi_int jackal_n3_01_H10_noSlack_inequalities_0_n_out(void) { return 2;}

casadi_real jackal_n3_01_H10_noSlack_inequalities_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* jackal_n3_01_H10_noSlack_inequalities_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* jackal_n3_01_H10_noSlack_inequalities_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* jackal_n3_01_H10_noSlack_inequalities_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* jackal_n3_01_H10_noSlack_inequalities_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

int jackal_n3_01_H10_noSlack_inequalities_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* jackal_n3_01_H10_noSlack_cdyn_0:(i0[8],i1[2],i2[27])->(o0[8],o1[2x8,2nz],o2[8x8,5nz]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
  a0=arg[0]? arg[0][2] : 0;
  a1=cos(a0);
  a2=arg[0]? arg[0][6] : 0;
  a3=(a1*a2);
  if (res[0]!=0) res[0][0]=a3;
  a3=sin(a0);
  a4=(a3*a2);
  if (res[0]!=0) res[0][1]=a4;
  a4=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][2]=a4;
  a4=0.;
  if (res[0]!=0) res[0][3]=a4;
  if (res[0]!=0) res[0][4]=a4;
  if (res[0]!=0) res[0][5]=a4;
  a4=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][6]=a4;
  a4=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][7]=a4;
  a4=1.;
  if (res[1]!=0) res[1][0]=a4;
  if (res[1]!=0) res[1][1]=a4;
  a5=sin(a0);
  a5=(a2*a5);
  a5=(-a5);
  if (res[2]!=0) res[2][0]=a5;
  if (res[2]!=0) res[2][1]=a1;
  a0=cos(a0);
  a2=(a2*a0);
  if (res[2]!=0) res[2][2]=a2;
  if (res[2]!=0) res[2][3]=a3;
  if (res[2]!=0) res[2][4]=a4;
  return 0;
}

int jackal_n3_01_H10_noSlack_cdyn_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

int jackal_n3_01_H10_noSlack_cdyn_0_alloc_mem(void) {
  return 0;
}

int jackal_n3_01_H10_noSlack_cdyn_0_init_mem(int mem) {
  return 0;
}

void jackal_n3_01_H10_noSlack_cdyn_0_free_mem(int mem) {
}

int jackal_n3_01_H10_noSlack_cdyn_0_checkout(void) {
  return 0;
}

void jackal_n3_01_H10_noSlack_cdyn_0_release(int mem) {
}

void jackal_n3_01_H10_noSlack_cdyn_0_incref(void) {
}

void jackal_n3_01_H10_noSlack_cdyn_0_decref(void) {
}

casadi_int jackal_n3_01_H10_noSlack_cdyn_0_n_in(void) { return 3;}

casadi_int jackal_n3_01_H10_noSlack_cdyn_0_n_out(void) { return 3;}

casadi_real jackal_n3_01_H10_noSlack_cdyn_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* jackal_n3_01_H10_noSlack_cdyn_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

const char* jackal_n3_01_H10_noSlack_cdyn_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

const casadi_int* jackal_n3_01_H10_noSlack_cdyn_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* jackal_n3_01_H10_noSlack_cdyn_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s8;
    case 2: return casadi_s9;
    default: return 0;
  }
}

int jackal_n3_01_H10_noSlack_cdyn_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* jackal_n3_01_H10_noSlack_cdyn_0rd_0:(i0[8],i1[2],i2[27])->(o0[8]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2;
  a0=arg[0]? arg[0][2] : 0;
  a1=cos(a0);
  a2=arg[0]? arg[0][6] : 0;
  a1=(a1*a2);
  if (res[0]!=0) res[0][0]=a1;
  a0=sin(a0);
  a0=(a0*a2);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=0.;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][7]=a0;
  return 0;
}

int jackal_n3_01_H10_noSlack_cdyn_0rd_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

int jackal_n3_01_H10_noSlack_cdyn_0rd_0_alloc_mem(void) {
  return 0;
}

int jackal_n3_01_H10_noSlack_cdyn_0rd_0_init_mem(int mem) {
  return 0;
}

void jackal_n3_01_H10_noSlack_cdyn_0rd_0_free_mem(int mem) {
}

int jackal_n3_01_H10_noSlack_cdyn_0rd_0_checkout(void) {
  return 0;
}

void jackal_n3_01_H10_noSlack_cdyn_0rd_0_release(int mem) {
}

void jackal_n3_01_H10_noSlack_cdyn_0rd_0_incref(void) {
}

void jackal_n3_01_H10_noSlack_cdyn_0rd_0_decref(void) {
}

casadi_int jackal_n3_01_H10_noSlack_cdyn_0rd_0_n_in(void) { return 3;}

casadi_int jackal_n3_01_H10_noSlack_cdyn_0rd_0_n_out(void) { return 1;}

casadi_real jackal_n3_01_H10_noSlack_cdyn_0rd_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* jackal_n3_01_H10_noSlack_cdyn_0rd_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

const char* jackal_n3_01_H10_noSlack_cdyn_0rd_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* jackal_n3_01_H10_noSlack_cdyn_0rd_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* jackal_n3_01_H10_noSlack_cdyn_0rd_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

int jackal_n3_01_H10_noSlack_cdyn_0rd_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* jackal_n3_01_H10_noSlack_objective_1:(i0[10],i1[27])->(o0,o1[1x10,5nz]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a3, a4, a5, a6, a7, a8, a9;
  a0=2.0000000000000001e-01;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a2=(a0*a2);
  a3=arg[0]? arg[0][0] : 0;
  a2=(a2+a3);
  a4=arg[1]? arg[1][17] : 0;
  a2=(a2-a4);
  a4=arg[1]? arg[1][20] : 0;
  a5=(a4*a2);
  a6=(a2*a5);
  a7=sin(a1);
  a7=(a0*a7);
  a8=arg[0]? arg[0][1] : 0;
  a7=(a7+a8);
  a9=arg[1]? arg[1][18] : 0;
  a7=(a7-a9);
  a9=arg[1]? arg[1][21] : 0;
  a10=(a9*a7);
  a11=(a7*a10);
  a6=(a6+a11);
  a11=arg[1]? arg[1][19] : 0;
  a12=arg[1]? arg[1][22] : 0;
  a12=(a12*a11);
  a11=(a11*a12);
  a6=(a6+a11);
  a11=arg[1]? arg[1][23] : 0;
  a12=cos(a1);
  a12=(a0*a12);
  a12=(a12+a3);
  a13=arg[1]? arg[1][1] : 0;
  a12=(a12-a13);
  a13=casadi_sq(a12);
  a14=sin(a1);
  a14=(a0*a14);
  a14=(a14+a8);
  a8=arg[1]? arg[1][2] : 0;
  a14=(a14-a8);
  a8=casadi_sq(a14);
  a13=(a13+a8);
  a8=arg[1]? arg[1][3] : 0;
  a8=casadi_sq(a8);
  a13=(a13+a8);
  a13=sqrt(a13);
  a8=arg[1]? arg[1][4] : 0;
  a8=(a13-a8);
  a15=arg[1]? arg[1][0] : 0;
  a8=(a8-a15);
  a11=(a11/a8);
  a15=arg[1]? arg[1][25] : 0;
  a16=arg[1]? arg[1][5] : 0;
  a3=(a3-a16);
  a15=(a15/a3);
  a16=(a11+a15);
  a17=arg[1]? arg[1][26] : 0;
  a18=arg[0]? arg[0][8] : 0;
  a19=arg[1]? arg[1][11] : 0;
  a19=(a18-a19);
  a17=(a17/a19);
  a16=(a16+a17);
  a6=(a6+a16);
  a16=arg[1]? arg[1][15] : 0;
  a20=(a16*a18);
  a21=(a18*a20);
  a22=arg[0]? arg[0][9] : 0;
  a23=arg[1]? arg[1][16] : 0;
  a24=(a23*a22);
  a25=(a22*a24);
  a21=(a21+a25);
  a6=(a6+a21);
  if (res[0]!=0) res[0][0]=a6;
  a4=(a4*a2);
  a5=(a5+a4);
  a15=(a15/a3);
  a12=(a12+a12);
  a11=(a11/a8);
  a13=(a13+a13);
  a11=(a11/a13);
  a12=(a12*a11);
  a15=(a15+a12);
  a15=(a5-a15);
  if (res[1]!=0) res[1][0]=a15;
  a9=(a9*a7);
  a10=(a10+a9);
  a14=(a14+a14);
  a14=(a14*a11);
  a11=(a10-a14);
  if (res[1]!=0) res[1][1]=a11;
  a11=sin(a1);
  a12=(a0*a12);
  a11=(a11*a12);
  a12=cos(a1);
  a14=(a0*a14);
  a12=(a12*a14);
  a11=(a11-a12);
  a12=cos(a1);
  a10=(a0*a10);
  a12=(a12*a10);
  a11=(a11+a12);
  a1=sin(a1);
  a0=(a0*a5);
  a1=(a1*a0);
  a11=(a11-a1);
  if (res[1]!=0) res[1][2]=a11;
  a16=(a16*a18);
  a20=(a20+a16);
  a17=(a17/a19);
  a20=(a20-a17);
  if (res[1]!=0) res[1][3]=a20;
  a23=(a23*a22);
  a24=(a24+a23);
  if (res[1]!=0) res[1][4]=a24;
  return 0;
}

int jackal_n3_01_H10_noSlack_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

int jackal_n3_01_H10_noSlack_objective_1_alloc_mem(void) {
  return 0;
}

int jackal_n3_01_H10_noSlack_objective_1_init_mem(int mem) {
  return 0;
}

void jackal_n3_01_H10_noSlack_objective_1_free_mem(int mem) {
}

int jackal_n3_01_H10_noSlack_objective_1_checkout(void) {
  return 0;
}

void jackal_n3_01_H10_noSlack_objective_1_release(int mem) {
}

void jackal_n3_01_H10_noSlack_objective_1_incref(void) {
}

void jackal_n3_01_H10_noSlack_objective_1_decref(void) {
}

casadi_int jackal_n3_01_H10_noSlack_objective_1_n_in(void) { return 2;}

casadi_int jackal_n3_01_H10_noSlack_objective_1_n_out(void) { return 2;}

casadi_real jackal_n3_01_H10_noSlack_objective_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* jackal_n3_01_H10_noSlack_objective_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* jackal_n3_01_H10_noSlack_objective_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* jackal_n3_01_H10_noSlack_objective_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* jackal_n3_01_H10_noSlack_objective_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

int jackal_n3_01_H10_noSlack_objective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* jackal_n3_01_H10_noSlack_inequalities_1:(i0[10],i1[27])->(o0[11],o1[11x10,13nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8;
  a0=2.0000000000000001e-01;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a2=(a0*a2);
  a3=arg[0]? arg[0][0] : 0;
  a2=(a2+a3);
  a4=arg[1]? arg[1][1] : 0;
  a2=(a2-a4);
  a4=casadi_sq(a2);
  a5=sin(a1);
  a5=(a0*a5);
  a6=arg[0]? arg[0][1] : 0;
  a5=(a5+a6);
  a7=arg[1]? arg[1][2] : 0;
  a5=(a5-a7);
  a7=casadi_sq(a5);
  a4=(a4+a7);
  a7=arg[1]? arg[1][3] : 0;
  a7=casadi_sq(a7);
  a4=(a4+a7);
  a4=sqrt(a4);
  a7=arg[1]? arg[1][4] : 0;
  a7=(a4-a7);
  a8=arg[1]? arg[1][0] : 0;
  a7=(a7-a8);
  if (res[0]!=0) res[0][0]=a7;
  a7=arg[1]? arg[1][5] : 0;
  a7=(a3-a7);
  if (res[0]!=0) res[0][1]=a7;
  a7=arg[1]? arg[1][8] : 0;
  a7=(a7-a3);
  if (res[0]!=0) res[0][2]=a7;
  a7=arg[1]? arg[1][6] : 0;
  a7=(a6-a7);
  if (res[0]!=0) res[0][3]=a7;
  a7=arg[1]? arg[1][9] : 0;
  a7=(a7-a6);
  if (res[0]!=0) res[0][4]=a7;
  a7=arg[1]? arg[1][7] : 0;
  a7=(a1-a7);
  if (res[0]!=0) res[0][5]=a7;
  a7=arg[1]? arg[1][10] : 0;
  a7=(a7-a1);
  if (res[0]!=0) res[0][6]=a7;
  a7=arg[0]? arg[0][8] : 0;
  a6=arg[1]? arg[1][11] : 0;
  a6=(a7-a6);
  if (res[0]!=0) res[0][7]=a6;
  a6=arg[1]? arg[1][13] : 0;
  a6=(a6-a7);
  if (res[0]!=0) res[0][8]=a6;
  a6=arg[0]? arg[0][9] : 0;
  a7=arg[1]? arg[1][12] : 0;
  a7=(a6-a7);
  if (res[0]!=0) res[0][9]=a7;
  a7=arg[1]? arg[1][14] : 0;
  a7=(a7-a6);
  if (res[0]!=0) res[0][10]=a7;
  a7=(a2/a4);
  if (res[1]!=0) res[1][0]=a7;
  a7=1.;
  if (res[1]!=0) res[1][1]=a7;
  a6=-1.;
  if (res[1]!=0) res[1][2]=a6;
  a3=(a5/a4);
  if (res[1]!=0) res[1][3]=a3;
  if (res[1]!=0) res[1][4]=a7;
  if (res[1]!=0) res[1][5]=a6;
  a5=(a5+a5);
  a3=cos(a1);
  a3=(a0*a3);
  a5=(a5*a3);
  a2=(a2+a2);
  a1=sin(a1);
  a0=(a0*a1);
  a2=(a2*a0);
  a5=(a5-a2);
  a4=(a4+a4);
  a5=(a5/a4);
  if (res[1]!=0) res[1][6]=a5;
  if (res[1]!=0) res[1][7]=a7;
  if (res[1]!=0) res[1][8]=a6;
  if (res[1]!=0) res[1][9]=a7;
  if (res[1]!=0) res[1][10]=a6;
  if (res[1]!=0) res[1][11]=a7;
  if (res[1]!=0) res[1][12]=a6;
  return 0;
}

int jackal_n3_01_H10_noSlack_inequalities_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

int jackal_n3_01_H10_noSlack_inequalities_1_alloc_mem(void) {
  return 0;
}

int jackal_n3_01_H10_noSlack_inequalities_1_init_mem(int mem) {
  return 0;
}

void jackal_n3_01_H10_noSlack_inequalities_1_free_mem(int mem) {
}

int jackal_n3_01_H10_noSlack_inequalities_1_checkout(void) {
  return 0;
}

void jackal_n3_01_H10_noSlack_inequalities_1_release(int mem) {
}

void jackal_n3_01_H10_noSlack_inequalities_1_incref(void) {
}

void jackal_n3_01_H10_noSlack_inequalities_1_decref(void) {
}

casadi_int jackal_n3_01_H10_noSlack_inequalities_1_n_in(void) { return 2;}

casadi_int jackal_n3_01_H10_noSlack_inequalities_1_n_out(void) { return 2;}

casadi_real jackal_n3_01_H10_noSlack_inequalities_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* jackal_n3_01_H10_noSlack_inequalities_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* jackal_n3_01_H10_noSlack_inequalities_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* jackal_n3_01_H10_noSlack_inequalities_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* jackal_n3_01_H10_noSlack_inequalities_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

int jackal_n3_01_H10_noSlack_inequalities_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
